language: perl
perl:
  - "5.6.2"
  - "5.8.1"
  - "5.8"
  - "5.8.9-thr"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.20.0-thr"
  - "blead"
before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
install:
  - cpan-install Test::More Devel::GlobalDestruction MRO::Compat
script: prove -l -r t
# vim: ts=2 sts=2 sw=2 et:
